/*
 * Copyright 2025 Humaid Alqasimi
 * SPDX-License-Identifier: Apache-2.0
 */
package db

import "errors"

var (
	ErrDatabaseConnectionNotInitialized = errors.New("database connection not initialized")
	ErrDatabaseURLEnvVarNotSet          = errors.New("DATABASE_URL environment variable is not set")
	ErrDatabaseNameNotSpecified         = errors.New("no database name specified in DATABASE_URL")

	ErrDisplayNameRequired = errors.New("display name is required")
	ErrUserNotFound        = errors.New("user not found")
	ErrInvalidUserHandle   = errors.New("invalid user handle")
	ErrPasskeyNotFound     = errors.New("passkey not found")

	ErrCardDAVConfigIncomplete       = errors.New("CardDAV configuration incomplete: CARDDAV_URL, CARDDAV_USERNAME, and CARDDAV_PASSWORD must all be set")
	ErrContactNotLinkedToCardDAV     = errors.New("contact is not linked to CardDAV")
	ErrContactAlreadyLinkedToCardDAV = errors.New("contact is already linked to CardDAV")
	ErrCardDAVContactByUUIDNotFound  = errors.New("contact with UUID not found")
	ErrCardDAVContactByUIDNotFound   = errors.New("contact with UID not found")
	ErrFetchVCFFileFailed            = errors.New("failed to fetch VCF file")

	ErrLogNotFound         = errors.New("log not found")
	ErrChatMessageRequired = errors.New("chat message is required")
	ErrChatEntryNotFound   = errors.New("chat entry not found")
	ErrNoteContentEmpty    = errors.New("note content cannot be empty")
	ErrNoteNotFound        = errors.New("note not found")
	ErrContactNotFound     = errors.New("contact not found")

	ErrContactExchangeLinkInvalid       = errors.New("contact exchange link is invalid")
	ErrContactExchangeCollectFieldEmpty = errors.New("contact exchange requires at least one field")

	ErrInvalidUserID    = errors.New("invalid user ID")
	ErrInvalidCreatorID = errors.New("invalid creator ID")
	ErrInvalidProfileID = errors.New("invalid profile ID")

	ErrNameRequired                = errors.New("name is required")
	ErrInventoryTypeInvalid        = errors.New("inventory type is invalid")
	ErrInventoryTagNameInvalid     = errors.New("inventory tag name is invalid")
	ErrCommentContentEmpty         = errors.New("comment content cannot be empty")
	ErrInventoryItemNotFound       = errors.New("inventory item not found")
	ErrCommentNotFound             = errors.New("comment not found")
	ErrLocationNotFound            = errors.New("location not found")
	ErrCategoryNameRequired        = errors.New("category name is required")
	ErrAmountMustBeGreaterThanZero = errors.New("amount must be greater than zero")
	ErrBudgetNotFound              = errors.New("budget not found")
	ErrAccountNameRequired         = errors.New("account name is required")
	ErrAccountTypeRequired         = errors.New("account type is required")
	ErrAccountNotFound             = errors.New("account not found")
	ErrMerchantRequired            = errors.New("merchant is required")
	ErrAmountMustBeNonZero         = errors.New("amount must be non-zero")
	ErrTransactionNotFound         = errors.New("transaction not found")
	ErrReconciliationNotFound      = errors.New("reconciliation not found")

	ErrOllamaConfigIncomplete      = errors.New("ollama configuration incomplete: OLLAMA_URL and OLLAMA_MODEL must be set")
	ErrOllamaReturnedStatus        = errors.New("ollama returned status")
	ErrOllamaError                 = errors.New("ollama error")
	ErrNoQRZAPIKeysProvided        = errors.New("no QRZ API keys provided")
	ErrQRZUserAgentNotConfigured   = errors.New("QRZ_USERAGENT not configured")
	ErrSyncAllQRZLogbooksFailed    = errors.New("failed to sync all QRZ logbooks")
	ErrQRZPaginationMissingLogID   = errors.New("unable to continue QRZ pagination (missing APP_QRZLOG_LOGID)")
	ErrQRZPaginationLimitReached   = errors.New("QRZ pagination limit reached")
	ErrQRZLogbookAPIReturnedStatus = errors.New("QRZ logbook API returned status")
	ErrQRZLogbookAPIError          = errors.New("QRZ logbook API error")
	ErrQRZLogbookResponseMissing   = errors.New("QRZ logbook response missing RESULT")

	ErrQSOIDRequired          = errors.New("qso id is required")
	ErrCallsignRequired       = errors.New("callsign is required")
	ErrMailingAddressRequired = errors.New("mailing address is required")
	ErrRequestIDRequired      = errors.New("request id is required")
	ErrQSLCardRequestNotFound = errors.New("qsl card request not found")

	ErrQRZXMLCredentialsNotConfigured = errors.New("qrz xml credentials are not configured (set QRZ_XML_USERNAME and QRZ_XML_PASSWORD)")
	ErrQRZXMLServiceURLInvalid        = errors.New("qrz xml service url is invalid")
	ErrQRZXMLAPIReturnedStatus        = errors.New("qrz xml api returned status")
	ErrQRZXMLResponseMalformed        = errors.New("qrz xml response malformed")
	ErrQRZXMLLoginFailed              = errors.New("qrz xml login failed")
	ErrQRZXMLSessionKeyMissing        = errors.New("qrz xml session key missing")
	ErrQRZXMLLookupFailed             = errors.New("qrz xml callsign lookup failed")

	ErrInvalidDateFormat = errors.New("invalid date format")
	ErrInvalidTimeFormat = errors.New("invalid time format")
	ErrUnableToParseDate = errors.New("unable to parse date")

	ErrInvalidPostgresSessionIniterArgument = errors.New("invalid PostgresSessionIniter argument")
	ErrNoTagIDsProvided                     = errors.New("no tag IDs provided")

	ErrWebDAVTodoPathNotConfigured       = errors.New("WEBDAV_TODO_PATH not configured")
	ErrWebDAVTodoPathMustBeOrgFile       = errors.New("WEBDAV_TODO_PATH must point to a .org file")
	ErrNoWebDAVPathsConfigured           = errors.New("no WebDAV paths configured")
	ErrWebDAVInventoryPathNotConfigured  = errors.New("WEBDAV_INV_PATH not configured")
	ErrWebDAVFilesPathNotConfigured      = errors.New("WEBDAV_FILES_PATH not configured")
	ErrWebDAVPublicPathNotConfigured     = errors.New("WEBDAV_PUBLIC_PATH not configured")
	ErrWebDAVFilesEntryETagRequired      = errors.New("files entry etag is required")
	ErrWebDAVFilesEntryExists            = errors.New("files entry already exists")
	ErrWebDAVFilesEntryNotFound          = errors.New("files entry not found")
	ErrWebDAVFilesEntryIsDirectory       = errors.New("files entry is a directory")
	ErrWebDAVFilesEntryNotDirectory      = errors.New("files entry is not a directory")
	ErrWebDAVFilesDirectoryNotEmpty      = errors.New("files directory is not empty")
	ErrWebDAVFilesEntryConflict          = errors.New("files entry conflict")
	ErrWebDAVFilesDirectoryPathRequired  = errors.New("directory path is required")
	ErrWebDAVFilesUploadPathNotDirectory = errors.New("upload path is not a directory")
	ErrWebDAVFilesUploadReaderNil        = errors.New("upload reader is nil")
	ErrWebDAVFilesUploadSizeUnknown      = errors.New("upload size unknown")
	ErrWebDAVFilesUploadSizeMismatch     = errors.New("upload size mismatch")
	ErrWebDAVFilesUploadHTTPStatus       = errors.New("files upload returned unexpected HTTP status")
	ErrWebDAVFilesUpdateHTTPStatus       = errors.New("files update returned unexpected HTTP status")
	ErrWebDAVZKPathNotConfigured         = errors.New("WEBDAV_ZK_PATH not configured")
	ErrWebDAVZKPathMustIncludeFilename   = errors.New("WEBDAV_ZK_PATH must include a filename")
	ErrWebDAVZKPathMustBeOrgFile         = errors.New("WEBDAV_ZK_PATH must point to a .org file")
	ErrWebDAVHomePathNotConfigured       = errors.New("WEBDAV_HOME_PATH not configured")
	ErrWebDAVHomePathMustIncludeFilename = errors.New("WEBDAV_HOME_PATH must include a filename")
	ErrWebDAVHomePathMustBeOrgFile       = errors.New("WEBDAV_HOME_PATH must point to a .org file")
	ErrWebDAVHomePathMustShareParentDir  = errors.New("WEBDAV_HOME_PATH must share the same parent directory as WEBDAV_ZK_PATH")
	ErrFetchTodoFileFailed               = errors.New("failed to fetch todo file")
	ErrFetchFileFailed                   = errors.New("failed to fetch file")
	ErrZKNoteNotFound                    = errors.New("note with ID not found")

	ErrInviteNotFound = errors.New("invite not found")
)
